version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/root/back
      override: yes
file_exists_behavior: OVERWRITE
hooks:
    ApplicationStop:
        - location: scripts/applicationStop.sh
    AfterInstall:
        - location: scripts/afterInstall.sh
